# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160210_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='location',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.AlterModelTable(
            name='stock',
            table=None,
        ),
        migrations.DeleteModel(
            name='Continent',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
